// Canonical inventory of Graphology methods that can change graph structure
// or attributes. Runtime draft guards and the static architecture test share
// this list so a newly used alias cannot bypass one layer while passing the
// other.
export const GRAPH_MUTATION_METHODS = [
  'replaceAttributes',
  'mergeAttributes',
  'setAttribute',
  'updateAttribute',
  'updateAttributes',
  'removeAttribute',
  'addNode',
  'mergeNode',
  'updateNode',
  'mergeNodeAttributes',
  'replaceNodeAttributes',
  'setNodeAttribute',
  'setNodeAttributes',
  'updateNodeAttribute',
  'updateNodeAttributes',
  'removeNodeAttribute',
  'updateEachNodeAttributes',
  'dropNode',
  'addEdge',
  'addEdgeWithKey',
  'addDirectedEdge',
  'addDirectedEdgeWithKey',
  'addUndirectedEdge',
  'addUndirectedEdgeWithKey',
  'mergeEdge',
  'mergeEdgeWithKey',
  'mergeDirectedEdge',
  'mergeDirectedEdgeWithKey',
  'mergeUndirectedEdge',
  'mergeUndirectedEdgeWithKey',
  'updateEdge',
  'updateEdgeWithKey',
  'updateDirectedEdge',
  'updateDirectedEdgeWithKey',
  'updateUndirectedEdge',
  'updateUndirectedEdgeWithKey',
  'dropEdge',
  'dropDirectedEdge',
  'dropUndirectedEdge',
  'mergeEdgeAttributes',
  'mergeDirectedEdgeAttributes',
  'mergeUndirectedEdgeAttributes',
  'replaceEdgeAttributes',
  'replaceDirectedEdgeAttributes',
  'replaceUndirectedEdgeAttributes',
  'setEdgeAttribute',
  'setDirectedEdgeAttribute',
  'setUndirectedEdgeAttribute',
  'setEdgeAttributes',
  'updateEdgeAttribute',
  'updateDirectedEdgeAttribute',
  'updateUndirectedEdgeAttribute',
  'updateEdgeAttributes',
  'updateDirectedEdgeAttributes',
  'updateUndirectedEdgeAttributes',
  'removeEdgeAttribute',
  'removeDirectedEdgeAttribute',
  'removeUndirectedEdgeAttribute',
  'mergeSourceAttributes',
  'mergeTargetAttributes',
  'mergeOppositeAttributes',
  'replaceSourceAttributes',
  'replaceTargetAttributes',
  'replaceOppositeAttributes',
  'setSourceAttribute',
  'setTargetAttribute',
  'setOppositeAttribute',
  'updateSourceAttribute',
  'updateTargetAttribute',
  'updateOppositeAttribute',
  'updateSourceAttributes',
  'updateTargetAttributes',
  'updateOppositeAttributes',
  'removeSourceAttribute',
  'removeTargetAttribute',
  'removeOppositeAttribute',
  'updateEachEdgeAttributes',
  'clearEdges',
  'clear',
  'import',
] as const;

export type GraphMutationMethod = typeof GRAPH_MUTATION_METHODS[number];
