/* eslint-disable */
// AUTO-GENERATED by scripts/gen-dashboard-api.ts. DO NOT EDIT.
// Dashboard compatibility v1; schema SHA-256 ffcb86dad6b3557f3c4744891e66236297a4d6297ba49ea84e422e440d86ca37

import {
  DashboardHttpRegistry,
  buildDashboardPath,
  responseSchemaFor,
} from '@overwatch/dashboard-api-contracts';
import type {
  DashboardBodyInput,
  DashboardEndpoint,
  DashboardPathInput,
  DashboardQueryInput,
  DashboardSuccessOutput,
} from '@overwatch/dashboard-api-contracts';
import { dashboardFetch } from './dashboard-transport';

export const DASHBOARD_API_SCHEMA_HASH = "ffcb86dad6b3557f3c4744891e66236297a4d6297ba49ea84e422e440d86ca37" as const;
export type GeneratedDashboardOperationId =
  | "actOnCampaign"
  | "answerAgentQueriesBatch"
  | "answerAgentQuery"
  | "approveAction"
  | "approveActionsBatch"
  | "bundleEngagement"
  | "cancelAgent"
  | "cloneCampaign"
  | "closeSession"
  | "correctGraph"
  | "createCampaign"
  | "createEngagement"
  | "createEngagementFromTemplate"
  | "createObjective"
  | "deleteCampaign"
  | "deleteObjective"
  | "deleteReport"
  | "denyAction"
  | "denyActionsBatch"
  | "dismissAgent"
  | "dismissFleetAgents"
  | "dispatchAgent"
  | "dispatchAgentBatch"
  | "dispatchCampaign"
  | "downloadReport"
  | "explainAction"
  | "exportGraph"
  | "findPaths"
  | "getActionOutput"
  | "getActiveApplicationCommands"
  | "getAgentArchetypes"
  | "getAgentConsole"
  | "getAgentContext"
  | "getAgentHistory"
  | "getAgentQueries"
  | "getAgents"
  | "getApplicationCommand"
  | "getCampaign"
  | "getCampaignChildren"
  | "getConfig"
  | "getDecisionLog"
  | "getEngagement"
  | "getEvidenceChains"
  | "getEvidenceImage"
  | "getEvidenceRaw"
  | "getFindingContext"
  | "getFindings"
  | "getFrontierWeights"
  | "getGraph"
  | "getHealth"
  | "getHistory"
  | "getInferenceRules"
  | "getMcpTools"
  | "getObjectivePaths"
  | "getOperatorConsole"
  | "getOpsecBudget"
  | "getParsers"
  | "getPendingActions"
  | "getPhases"
  | "getPlaybookRun"
  | "getProposedPlans"
  | "getReadiness"
  | "getRecovery"
  | "getSessionBuffer"
  | "getSessions"
  | "getSettings"
  | "getState"
  | "getTapeStatus"
  | "getTelemetry"
  | "getTemplates"
  | "getTimeline"
  | "getTools"
  | "getTrustSignals"
  | "interpretCommand"
  | "interruptPlaybookAttempt"
  | "issueAgentDirective"
  | "issueFleetDirective"
  | "listCampaigns"
  | "listEngagements"
  | "listPlaybookRuns"
  | "listReports"
  | "previewScope"
  | "quickDeployAgent"
  | "renderReport"
  | "reparseAction"
  | "resetFrontierWeights"
  | "resolveConfigDivergence"
  | "resumePlaybookRun"
  | "resumeSession"
  | "retryPlaybookStep"
  | "skipPlaybookStep"
  | "splitCampaign"
  | "startPlaybookStep"
  | "toggleTape"
  | "updateCampaign"
  | "updateConfig"
  | "updateEngagement"
  | "updateFrontierWeights"
  | "updateObjective"
  | "updateScope"
  | "updateSession"
  | "updateSettings";

export interface GeneratedDashboardRequest {
  path?: Record<string, unknown>;
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: HeadersInit;
  signal?: AbortSignal;
  cache?: RequestCache;
}
export type GeneratedDashboardRequestFor<T extends GeneratedDashboardOperationId> =
  Omit<GeneratedDashboardRequest, 'path' | 'query' | 'body'> & {
    path?: DashboardPathInput<T>;
    query?: DashboardQueryInput<T>;
    body?: DashboardBodyInput<T>;
  };
export type GeneratedDashboardOutput<T extends GeneratedDashboardOperationId> =
  DashboardEndpoint<T>['response_kind'] extends 'binary'
    ? Response
    : DashboardSuccessOutput<T>;

export class DashboardApiError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly code?: string,
    readonly body?: unknown,
  ) {
    super(message);
    this.name = 'DashboardApiError';
  }
}

type DashboardApiErrorObserver = (error: DashboardApiError) => void;
let errorObserver: DashboardApiErrorObserver | undefined;
export function setDashboardApiErrorObserver(observer?: DashboardApiErrorObserver): void {
  errorObserver = observer;
}

function appendQuery(search: URLSearchParams, query: Record<string, unknown>): void {
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null || key === 'token') continue;
    if (Array.isArray(value)) {
      for (const item of value) search.append(key, String(item));
    } else {
      search.set(key, String(value));
    }
  }
}

export async function requestDashboardEndpoint<T extends GeneratedDashboardOperationId>(
  operationId: T,
  input: GeneratedDashboardRequestFor<T> = {},
): Promise<GeneratedDashboardOutput<T>> {
  const endpoint = DashboardHttpRegistry[operationId];
  if (!endpoint) throw new Error(`Unknown dashboard operation: ${operationId}`);
  const path = buildDashboardPath(operationId, input.path ?? {});
  const query = endpoint.query_schema.parse(input.query ?? {}) as Record<string, unknown>;
  const search = new URLSearchParams();
  appendQuery(search, query);
  const url = `${path}${search.size > 0 ? `?${search.toString()}` : ''}`;
  const body = endpoint.body_schema.parse(input.body);
  const headers = new Headers(input.headers);
  if (body !== undefined && !headers.has('Content-Type')) headers.set('Content-Type', 'application/json');
  const response = await dashboardFetch(url, {
    method: endpoint.method,
    headers,
    ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
    ...(input.signal ? { signal: input.signal } : {}),
    ...(input.cache ? { cache: input.cache } : {}),
  });
  const registeredSchema = responseSchemaFor(endpoint, response.status);
  const explicitlyRegistered = Object.prototype.hasOwnProperty.call(endpoint.responses, response.status);
  if (endpoint.response_kind === 'binary' && explicitlyRegistered) {
    return response as GeneratedDashboardOutput<T>;
  }

  const raw = await response.text().catch(() => '');
  let payload: unknown;
  try {
    payload = raw ? JSON.parse(raw) : undefined;
  } catch {
    payload = raw;
  }

  if (registeredSchema) {
    const parsed = registeredSchema.safeParse(payload);
    if (!parsed.success) {
      const error = new DashboardApiError(
        `Dashboard response contract failed for ${operationId} (${response.status})`,
        response.status,
        'DASHBOARD_RESPONSE_CONTRACT_FAILED',
        { issues: parsed.error.issues, payload },
      );
      errorObserver?.(error);
      throw error;
    }
    payload = parsed.data;
    if (explicitlyRegistered) return parsed.data as GeneratedDashboardOutput<T>;
  }

  const record = payload && typeof payload === 'object' ? payload as Record<string, unknown> : undefined;
  const detail = typeof record?.error === 'string' ? record.error : raw;
  const prefix = `${response.status}${response.statusText ? ` ${response.statusText}` : ''}`;
  const error = new DashboardApiError(
    `${prefix}${detail ? `: ${detail}` : ''}`,
    response.status,
    typeof record?.code === 'string' ? record.code : undefined,
    payload,
  );
  errorObserver?.(error);
  throw error;
}

export const requestActOnCampaign = (input: GeneratedDashboardRequestFor<"actOnCampaign"> = {}) => requestDashboardEndpoint("actOnCampaign", input);
export const requestAnswerAgentQueriesBatch = (input: GeneratedDashboardRequestFor<"answerAgentQueriesBatch"> = {}) => requestDashboardEndpoint("answerAgentQueriesBatch", input);
export const requestAnswerAgentQuery = (input: GeneratedDashboardRequestFor<"answerAgentQuery"> = {}) => requestDashboardEndpoint("answerAgentQuery", input);
export const requestApproveAction = (input: GeneratedDashboardRequestFor<"approveAction"> = {}) => requestDashboardEndpoint("approveAction", input);
export const requestApproveActionsBatch = (input: GeneratedDashboardRequestFor<"approveActionsBatch"> = {}) => requestDashboardEndpoint("approveActionsBatch", input);
export const requestBundleEngagement = (input: GeneratedDashboardRequestFor<"bundleEngagement"> = {}) => requestDashboardEndpoint("bundleEngagement", input);
export const requestCancelAgent = (input: GeneratedDashboardRequestFor<"cancelAgent"> = {}) => requestDashboardEndpoint("cancelAgent", input);
export const requestCloneCampaign = (input: GeneratedDashboardRequestFor<"cloneCampaign"> = {}) => requestDashboardEndpoint("cloneCampaign", input);
export const requestCloseSession = (input: GeneratedDashboardRequestFor<"closeSession"> = {}) => requestDashboardEndpoint("closeSession", input);
export const requestCorrectGraph = (input: GeneratedDashboardRequestFor<"correctGraph"> = {}) => requestDashboardEndpoint("correctGraph", input);
export const requestCreateCampaign = (input: GeneratedDashboardRequestFor<"createCampaign"> = {}) => requestDashboardEndpoint("createCampaign", input);
export const requestCreateEngagement = (input: GeneratedDashboardRequestFor<"createEngagement"> = {}) => requestDashboardEndpoint("createEngagement", input);
export const requestCreateEngagementFromTemplate = (input: GeneratedDashboardRequestFor<"createEngagementFromTemplate"> = {}) => requestDashboardEndpoint("createEngagementFromTemplate", input);
export const requestCreateObjective = (input: GeneratedDashboardRequestFor<"createObjective"> = {}) => requestDashboardEndpoint("createObjective", input);
export const requestDeleteCampaign = (input: GeneratedDashboardRequestFor<"deleteCampaign"> = {}) => requestDashboardEndpoint("deleteCampaign", input);
export const requestDeleteObjective = (input: GeneratedDashboardRequestFor<"deleteObjective"> = {}) => requestDashboardEndpoint("deleteObjective", input);
export const requestDeleteReport = (input: GeneratedDashboardRequestFor<"deleteReport"> = {}) => requestDashboardEndpoint("deleteReport", input);
export const requestDenyAction = (input: GeneratedDashboardRequestFor<"denyAction"> = {}) => requestDashboardEndpoint("denyAction", input);
export const requestDenyActionsBatch = (input: GeneratedDashboardRequestFor<"denyActionsBatch"> = {}) => requestDashboardEndpoint("denyActionsBatch", input);
export const requestDismissAgent = (input: GeneratedDashboardRequestFor<"dismissAgent"> = {}) => requestDashboardEndpoint("dismissAgent", input);
export const requestDismissFleetAgents = (input: GeneratedDashboardRequestFor<"dismissFleetAgents"> = {}) => requestDashboardEndpoint("dismissFleetAgents", input);
export const requestDispatchAgent = (input: GeneratedDashboardRequestFor<"dispatchAgent"> = {}) => requestDashboardEndpoint("dispatchAgent", input);
export const requestDispatchAgentBatch = (input: GeneratedDashboardRequestFor<"dispatchAgentBatch"> = {}) => requestDashboardEndpoint("dispatchAgentBatch", input);
export const requestDispatchCampaign = (input: GeneratedDashboardRequestFor<"dispatchCampaign"> = {}) => requestDashboardEndpoint("dispatchCampaign", input);
export const requestDownloadReport = (input: GeneratedDashboardRequestFor<"downloadReport"> = {}) => requestDashboardEndpoint("downloadReport", input);
export const requestExplainAction = (input: GeneratedDashboardRequestFor<"explainAction"> = {}) => requestDashboardEndpoint("explainAction", input);
export const requestExportGraph = (input: GeneratedDashboardRequestFor<"exportGraph"> = {}) => requestDashboardEndpoint("exportGraph", input);
export const requestFindPaths = (input: GeneratedDashboardRequestFor<"findPaths"> = {}) => requestDashboardEndpoint("findPaths", input);
export const requestGetActionOutput = (input: GeneratedDashboardRequestFor<"getActionOutput"> = {}) => requestDashboardEndpoint("getActionOutput", input);
export const requestGetActiveApplicationCommands = (input: GeneratedDashboardRequestFor<"getActiveApplicationCommands"> = {}) => requestDashboardEndpoint("getActiveApplicationCommands", input);
export const requestGetAgentArchetypes = (input: GeneratedDashboardRequestFor<"getAgentArchetypes"> = {}) => requestDashboardEndpoint("getAgentArchetypes", input);
export const requestGetAgentConsole = (input: GeneratedDashboardRequestFor<"getAgentConsole"> = {}) => requestDashboardEndpoint("getAgentConsole", input);
export const requestGetAgentContext = (input: GeneratedDashboardRequestFor<"getAgentContext"> = {}) => requestDashboardEndpoint("getAgentContext", input);
export const requestGetAgentHistory = (input: GeneratedDashboardRequestFor<"getAgentHistory"> = {}) => requestDashboardEndpoint("getAgentHistory", input);
export const requestGetAgentQueries = (input: GeneratedDashboardRequestFor<"getAgentQueries"> = {}) => requestDashboardEndpoint("getAgentQueries", input);
export const requestGetAgents = (input: GeneratedDashboardRequestFor<"getAgents"> = {}) => requestDashboardEndpoint("getAgents", input);
export const requestGetApplicationCommand = (input: GeneratedDashboardRequestFor<"getApplicationCommand"> = {}) => requestDashboardEndpoint("getApplicationCommand", input);
export const requestGetCampaign = (input: GeneratedDashboardRequestFor<"getCampaign"> = {}) => requestDashboardEndpoint("getCampaign", input);
export const requestGetCampaignChildren = (input: GeneratedDashboardRequestFor<"getCampaignChildren"> = {}) => requestDashboardEndpoint("getCampaignChildren", input);
export const requestGetConfig = (input: GeneratedDashboardRequestFor<"getConfig"> = {}) => requestDashboardEndpoint("getConfig", input);
export const requestGetDecisionLog = (input: GeneratedDashboardRequestFor<"getDecisionLog"> = {}) => requestDashboardEndpoint("getDecisionLog", input);
export const requestGetEngagement = (input: GeneratedDashboardRequestFor<"getEngagement"> = {}) => requestDashboardEndpoint("getEngagement", input);
export const requestGetEvidenceChains = (input: GeneratedDashboardRequestFor<"getEvidenceChains"> = {}) => requestDashboardEndpoint("getEvidenceChains", input);
export const requestGetEvidenceImage = (input: GeneratedDashboardRequestFor<"getEvidenceImage"> = {}) => requestDashboardEndpoint("getEvidenceImage", input);
export const requestGetEvidenceRaw = (input: GeneratedDashboardRequestFor<"getEvidenceRaw"> = {}) => requestDashboardEndpoint("getEvidenceRaw", input);
export const requestGetFindingContext = (input: GeneratedDashboardRequestFor<"getFindingContext"> = {}) => requestDashboardEndpoint("getFindingContext", input);
export const requestGetFindings = (input: GeneratedDashboardRequestFor<"getFindings"> = {}) => requestDashboardEndpoint("getFindings", input);
export const requestGetFrontierWeights = (input: GeneratedDashboardRequestFor<"getFrontierWeights"> = {}) => requestDashboardEndpoint("getFrontierWeights", input);
export const requestGetGraph = (input: GeneratedDashboardRequestFor<"getGraph"> = {}) => requestDashboardEndpoint("getGraph", input);
export const requestGetHealth = (input: GeneratedDashboardRequestFor<"getHealth"> = {}) => requestDashboardEndpoint("getHealth", input);
export const requestGetHistory = (input: GeneratedDashboardRequestFor<"getHistory"> = {}) => requestDashboardEndpoint("getHistory", input);
export const requestGetInferenceRules = (input: GeneratedDashboardRequestFor<"getInferenceRules"> = {}) => requestDashboardEndpoint("getInferenceRules", input);
export const requestGetMcpTools = (input: GeneratedDashboardRequestFor<"getMcpTools"> = {}) => requestDashboardEndpoint("getMcpTools", input);
export const requestGetObjectivePaths = (input: GeneratedDashboardRequestFor<"getObjectivePaths"> = {}) => requestDashboardEndpoint("getObjectivePaths", input);
export const requestGetOperatorConsole = (input: GeneratedDashboardRequestFor<"getOperatorConsole"> = {}) => requestDashboardEndpoint("getOperatorConsole", input);
export const requestGetOpsecBudget = (input: GeneratedDashboardRequestFor<"getOpsecBudget"> = {}) => requestDashboardEndpoint("getOpsecBudget", input);
export const requestGetParsers = (input: GeneratedDashboardRequestFor<"getParsers"> = {}) => requestDashboardEndpoint("getParsers", input);
export const requestGetPendingActions = (input: GeneratedDashboardRequestFor<"getPendingActions"> = {}) => requestDashboardEndpoint("getPendingActions", input);
export const requestGetPhases = (input: GeneratedDashboardRequestFor<"getPhases"> = {}) => requestDashboardEndpoint("getPhases", input);
export const requestGetPlaybookRun = (input: GeneratedDashboardRequestFor<"getPlaybookRun"> = {}) => requestDashboardEndpoint("getPlaybookRun", input);
export const requestGetProposedPlans = (input: GeneratedDashboardRequestFor<"getProposedPlans"> = {}) => requestDashboardEndpoint("getProposedPlans", input);
export const requestGetReadiness = (input: GeneratedDashboardRequestFor<"getReadiness"> = {}) => requestDashboardEndpoint("getReadiness", input);
export const requestGetRecovery = (input: GeneratedDashboardRequestFor<"getRecovery"> = {}) => requestDashboardEndpoint("getRecovery", input);
export const requestGetSessionBuffer = (input: GeneratedDashboardRequestFor<"getSessionBuffer"> = {}) => requestDashboardEndpoint("getSessionBuffer", input);
export const requestGetSessions = (input: GeneratedDashboardRequestFor<"getSessions"> = {}) => requestDashboardEndpoint("getSessions", input);
export const requestGetSettings = (input: GeneratedDashboardRequestFor<"getSettings"> = {}) => requestDashboardEndpoint("getSettings", input);
export const requestGetState = (input: GeneratedDashboardRequestFor<"getState"> = {}) => requestDashboardEndpoint("getState", input);
export const requestGetTapeStatus = (input: GeneratedDashboardRequestFor<"getTapeStatus"> = {}) => requestDashboardEndpoint("getTapeStatus", input);
export const requestGetTelemetry = (input: GeneratedDashboardRequestFor<"getTelemetry"> = {}) => requestDashboardEndpoint("getTelemetry", input);
export const requestGetTemplates = (input: GeneratedDashboardRequestFor<"getTemplates"> = {}) => requestDashboardEndpoint("getTemplates", input);
export const requestGetTimeline = (input: GeneratedDashboardRequestFor<"getTimeline"> = {}) => requestDashboardEndpoint("getTimeline", input);
export const requestGetTools = (input: GeneratedDashboardRequestFor<"getTools"> = {}) => requestDashboardEndpoint("getTools", input);
export const requestGetTrustSignals = (input: GeneratedDashboardRequestFor<"getTrustSignals"> = {}) => requestDashboardEndpoint("getTrustSignals", input);
export const requestInterpretCommand = (input: GeneratedDashboardRequestFor<"interpretCommand"> = {}) => requestDashboardEndpoint("interpretCommand", input);
export const requestInterruptPlaybookAttempt = (input: GeneratedDashboardRequestFor<"interruptPlaybookAttempt"> = {}) => requestDashboardEndpoint("interruptPlaybookAttempt", input);
export const requestIssueAgentDirective = (input: GeneratedDashboardRequestFor<"issueAgentDirective"> = {}) => requestDashboardEndpoint("issueAgentDirective", input);
export const requestIssueFleetDirective = (input: GeneratedDashboardRequestFor<"issueFleetDirective"> = {}) => requestDashboardEndpoint("issueFleetDirective", input);
export const requestListCampaigns = (input: GeneratedDashboardRequestFor<"listCampaigns"> = {}) => requestDashboardEndpoint("listCampaigns", input);
export const requestListEngagements = (input: GeneratedDashboardRequestFor<"listEngagements"> = {}) => requestDashboardEndpoint("listEngagements", input);
export const requestListPlaybookRuns = (input: GeneratedDashboardRequestFor<"listPlaybookRuns"> = {}) => requestDashboardEndpoint("listPlaybookRuns", input);
export const requestListReports = (input: GeneratedDashboardRequestFor<"listReports"> = {}) => requestDashboardEndpoint("listReports", input);
export const requestPreviewScope = (input: GeneratedDashboardRequestFor<"previewScope"> = {}) => requestDashboardEndpoint("previewScope", input);
export const requestQuickDeployAgent = (input: GeneratedDashboardRequestFor<"quickDeployAgent"> = {}) => requestDashboardEndpoint("quickDeployAgent", input);
export const requestRenderReport = (input: GeneratedDashboardRequestFor<"renderReport"> = {}) => requestDashboardEndpoint("renderReport", input);
export const requestReparseAction = (input: GeneratedDashboardRequestFor<"reparseAction"> = {}) => requestDashboardEndpoint("reparseAction", input);
export const requestResetFrontierWeights = (input: GeneratedDashboardRequestFor<"resetFrontierWeights"> = {}) => requestDashboardEndpoint("resetFrontierWeights", input);
export const requestResolveConfigDivergence = (input: GeneratedDashboardRequestFor<"resolveConfigDivergence"> = {}) => requestDashboardEndpoint("resolveConfigDivergence", input);
export const requestResumePlaybookRun = (input: GeneratedDashboardRequestFor<"resumePlaybookRun"> = {}) => requestDashboardEndpoint("resumePlaybookRun", input);
export const requestResumeSession = (input: GeneratedDashboardRequestFor<"resumeSession"> = {}) => requestDashboardEndpoint("resumeSession", input);
export const requestRetryPlaybookStep = (input: GeneratedDashboardRequestFor<"retryPlaybookStep"> = {}) => requestDashboardEndpoint("retryPlaybookStep", input);
export const requestSkipPlaybookStep = (input: GeneratedDashboardRequestFor<"skipPlaybookStep"> = {}) => requestDashboardEndpoint("skipPlaybookStep", input);
export const requestSplitCampaign = (input: GeneratedDashboardRequestFor<"splitCampaign"> = {}) => requestDashboardEndpoint("splitCampaign", input);
export const requestStartPlaybookStep = (input: GeneratedDashboardRequestFor<"startPlaybookStep"> = {}) => requestDashboardEndpoint("startPlaybookStep", input);
export const requestToggleTape = (input: GeneratedDashboardRequestFor<"toggleTape"> = {}) => requestDashboardEndpoint("toggleTape", input);
export const requestUpdateCampaign = (input: GeneratedDashboardRequestFor<"updateCampaign"> = {}) => requestDashboardEndpoint("updateCampaign", input);
export const requestUpdateConfig = (input: GeneratedDashboardRequestFor<"updateConfig"> = {}) => requestDashboardEndpoint("updateConfig", input);
export const requestUpdateEngagement = (input: GeneratedDashboardRequestFor<"updateEngagement"> = {}) => requestDashboardEndpoint("updateEngagement", input);
export const requestUpdateFrontierWeights = (input: GeneratedDashboardRequestFor<"updateFrontierWeights"> = {}) => requestDashboardEndpoint("updateFrontierWeights", input);
export const requestUpdateObjective = (input: GeneratedDashboardRequestFor<"updateObjective"> = {}) => requestDashboardEndpoint("updateObjective", input);
export const requestUpdateScope = (input: GeneratedDashboardRequestFor<"updateScope"> = {}) => requestDashboardEndpoint("updateScope", input);
export const requestUpdateSession = (input: GeneratedDashboardRequestFor<"updateSession"> = {}) => requestDashboardEndpoint("updateSession", input);
export const requestUpdateSettings = (input: GeneratedDashboardRequestFor<"updateSettings"> = {}) => requestDashboardEndpoint("updateSettings", input);
