// Generated by scripts/gen-public-inventories.ts. Do not edit.
export const TOOL_REGISTRY_SHA256 = "b64ba41aab7ee1b8d3c85e84f088e7aa0d195dd5e0cfbdcd3817a8dae434d00d";
export const TOOL_CATEGORIES = [
  {
    "id": "state-readiness",
    "label": "State & readiness",
    "order": 10,
    "count": 10
  },
  {
    "id": "execution-approval",
    "label": "Execution & approval",
    "order": 20,
    "count": 10
  },
  {
    "id": "graph-data",
    "label": "Graph & data",
    "order": 30,
    "count": 12
  },
  {
    "id": "agents-planning",
    "label": "Agents & planning",
    "order": 40,
    "count": 18
  },
  {
    "id": "credentials-playbooks",
    "label": "Credentials & playbooks",
    "order": 50,
    "count": 18
  },
  {
    "id": "sessions-runtime",
    "label": "Sessions & runtime",
    "order": 60,
    "count": 11
  },
  {
    "id": "config-scope",
    "label": "Configuration & scope",
    "order": 70,
    "count": 6
  },
  {
    "id": "audit-reporting",
    "label": "Audit & reporting",
    "order": 80,
    "count": 10
  }
] as const;
